name: Build ReiKey

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: pod install

      - name: Build with xcodebuild
        run: |
          xcodebuild -workspace ReiKey.xcworkspace -scheme ReiKey -configuration Release -derivedDataPath build

      - name: Zip .app
        run: |
          mkdir dist
          cp -R build/Build/Products/Release/ReiKey.app dist/
          cd dist && zip -r ReiKey.zip ReiKey.app

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ReiKey
          path: dist/ReiKey.zip
