name: Build ReiKey

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest Git
        run: |
          brew install git || true
          echo "export PATH=/opt/homebrew/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV
          git --version

      - name: Use new git in PATH
        run: echo "/opt/homebrew/bin:/usr/local/bin:$PATH" >> ~/.bash_profile

      - name: Export GitHub token for Carthage
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Install Carthage
        run: brew install carthage || true

      - name: Carthage bootstrap
        run: carthage bootstrap --platform macOS

      - name: List available Xcode schemes
        run: xcodebuild -list -workspace ReiKey.xcworkspace

      - name: Build with Xcode
        run: |
          xcodebuild -workspace ReiKey.xcworkspace \
                     -scheme mainApp \
                     -configuration Release \
                     clean build

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: ReiKey.app
          path: ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Release/mainApp.app
