jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install carthage

      - name: Bootstrap dependencies
        run: carthage bootstrap --platform macOS

      - name: List available Xcode schemes
        run: xcodebuild -list -workspace ReiKey.xcworkspace

      - name: Build with Xcode
        run: |
          xcodebuild -workspace ReiKey.xcworkspace \
                     -scheme ReiKey \
                     -configuration Release \
                     clean build
