name: Build ReiKey

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew dependencies
        run: |
          brew install carthage

      - name: Configure GitHub authentication for Carthage
        run: |
          echo "machine github.com login ${{ secrets.GH_TOKEN }}" >> ~/.netrc
          echo "machine api.github.com login ${{ secrets.GH_TOKEN }}" >> ~/.netrc

      - name: Bootstrap dependencies
        run: carthage bootstrap --platform macOS

      - name: Build project
        run: |
          xcodebuild -workspace ReiKey.xcworkspace \
                     -scheme ReiKey \
                     -configuration Release \
                     clean build

      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: ReiKey.app
          path: ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Release/ReiKey.app
