name: Build ReiKey

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest Git
        run: |
          brew install git || true
          git --version

      - name: Set GitHub token for Carthage
        run: echo "github.com=${{ secrets.GITHUB_TOKEN }}" > ~/.gitconfig

      - name: Install Carthage
        run: brew install carthage || true

      - name: Bootstrap dependencies
        run: carthage bootstrap --platform macOS

      - name: List available Xcode schemes
        run: xcodebuild -list -workspace ReiKey.xcworkspace

      - name: Build with Xcode
        run: |
          xcodebuild -workspace ReiKey.xcworkspace \
                     -scheme mainApp \
                     -configuration Release \
                     clean build
