name: Build ReiKey

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest Git
        run: |
          brew install git
          echo "Updated git version: $(git --version)"

      - name: Set GitHub token for Carthage
        run: echo "github.com=oauth:$GH_TOKEN" > ~/.gitconfig
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Carthage
        run: brew install carthage

      - name: Bootstrap dependencies
        run: carthage bootstrap --platform macOS

      - name: List available Xcode schemes
        run: xcodebuild -list -workspace ReiKey.xcworkspace

      - name: Build with Xcode
        run: |
          xcodebuild -workspace ReiKey.xcworkspace \
                     -scheme ReiKey \
                     -configuration Release \
                     clean build

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: ReiKey.app
          path: ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Release/ReiKey.app
