name: Build ReiKey

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest Git
        run: |
          brew install git || brew upgrade git
          git --version

      - name: Install Carthage
        run: brew install carthage

      - name: Set up git credentials for Carthage
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Bootstrap dependencies
        run: carthage bootstrap --platform macOS

      - name: List available Xcode schemes
        run: xcodebuild -list -workspace ReiKey.xcworkspace

      - name: Build with Xcode (no signing)
        run: |
          xcodebuild -workspace ReiKey.xcworkspace \
            -scheme mainApp \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            clean build
