name: Build ReiKey

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install carthage

      - name: Build project
        run: |
          xcodebuild -workspace ReiKey.xcworkspace \
                     -scheme ReiKey \
                     -configuration Release \
                     clean build

      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: ReiKey.app
          path: ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Release/ReiKey.app
